name: CI

on:
  pull_request:
    
jobs:
  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache bundle install
      uses: actions/cache@v2
      env:
        cache-name: cache-bundle-install
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install ruby gems for fastlane
      run: |
        bundle config path vendor/bundle
        bundle install

    - name: Run tests
      run: bundle exec fastlane verify_pull_request

    - name: Upload test output
      if: ${{ success() || failure() }} # always run even if the tests fail
      uses: actions/upload-artifact@v2
      with:
        name: test-output
        path: fastlane/test_output/

    - name: Report jUnit Annotations as Github Actions Annotations
      if: ${{ success() || failure() }}
      uses: shyim/junit-report-annotations-action@0.2.0
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        path: fastlane/test_output/report.junit
